### ISSUE TITLE
baseCountsFromBamList giving unexpected output

### ISSUE THREAD

**Issue by bdj34** [veltenlab/mitoClone#2]
Hello,

First, thanks for this tool, it seems like it will be very insightful if I can get it to work. 

My issue is that when I make `countTables` from the `baseCountsFromBamList` function, the output (`countTables`) is a list with one table for each sample instead of one table for each cell. In this example, it is a list of two instead of several hundred/thousand. 

Here's my code: 

```
library(pheatmap)
library(mitoClone)
library(deepSNV)
library(GenomicRanges)

bamdir <- '/PATH_TO_FOLDER_NAMED_BAM/BAM/'
bamfiles <- c(paste0(bamdir, 'fileName1.bam'), paste0(bamdir, 'fileName2.bam'))
countTables <- baseCountsFromBamList( bamfiles,  sites = "MT:1-16569", ncores = 16)
```

I'm using R version 4.0.3 and the output is a list of the two samples with a single count table for each. I should mention also that the bam index files are accessible within the same BAM directory as the bam files. In the vignettes it seems that this step is already done and the data is imported as a count table, but I was wondering if there is something wrong with the way I have run this function or if this might be an issue with the bam files I have.

**Comment by benstory** [comment]
What is `length(bamfiles)` it should be equal to the number of bam files you supplied to the function (i.e. bamfiles). 

The assumed input here is a single BAM file per cell.

**A single count table is produced per BAM file input**. At present, a method to de-multiplex an individual BAM file by cell within the variant pileup step is _under development_ and not yet available. If you have multiple cells within each BAM file,  my current recommendation would be to apply something akin to https://github.com/10XGenomics/subset-bam to split your individual BAM files into daughter BAM files for each cell they contain.

**Comment by bdj34** [comment]
Okay that clears it up, thank you! I had all cells from a given sample in one bam file and didn't know the assumed input was one bam file per cell.
