### ISSUE TITLE
Matrix M and N difference

### ISSUE THREAD

**Issue by yuhanH** [veltenlab/mitoClone#3]
I am wondering what are the difference of matrix M and matrix N which are generated by `mutationCallsFromCohort` and are used as input in function `mutationCallsFromMatrix`. 
The descriptions matrix M and N in `mutationCallsFromMatrix` seems to be same. 
```
M : A matrix of read counts mapping to the mutant allele. Columns are genomic sites and rows and single cells.
N : A matrix of read counts mapping to the mutant allele. Columns are genomic sites and rows and single cells.
```
Does matrix N represent WT allele?
Thanks.

**Comment by velten-lab** [comment]
Thank you for pointing this out. Indeed N represents the reference allele. I have updated the documentation.
